# Generated by Django 5.0.7 on 2026-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cancellation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='complaint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='completed_stays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='couple_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='emergency_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='family_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_24x7_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_verified_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_well_lit_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_women_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='local_experience_bundle',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='hotel',
            name='near_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='hotel',
            name='supports_late_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='verified_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='workspace_ready',
            field=models.BooleanField(default=False),
        ),
    ]
