# Generated by Django 5.0.7 on 2026-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_cancellation_count_hotel_complaint_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
